//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialChartPlugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MaterialChartSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MaterialChartSettings defaultInstance = ((MaterialChartSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MaterialChartSettings())));
        
        public static MaterialChartSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CsvRecordSummary {
            get {
                return ((bool)(this["CsvRecordSummary"]));
            }
            set {
                this["CsvRecordSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CsvRecordOrder {
            get {
                return ((bool)(this["CsvRecordOrder"]));
            }
            set {
                this["CsvRecordOrder"] = value;
            }
        }
    }
}
